env:
  global:
    - secure: YbQnVme846P9oJ9/zlkQ/6WT2+VloIqVq+k+e3OKuA8cmSkAV/zaH4QvPbe+A+9eoXe4zdAw5Jw595Cotg8JPScMAUQT7B4xRV6aaGwIocgJIxHEizUc2F13D+uyckIP9VJtkHzX3nQBnAYCukrIs2NRA6HrzsSGlEx0Nh1cj22d2cmKpanF3O6X0zhSEMi+aY8/Thqw0oIPHYgYkKWUIpSs7LWdpJ4nYTq54Sc20u4KSu6MgGXnKvc5jFG3MPFx+VTamLqYUwqeEfHFc2ipCc6OM9lkjHZCj7PYehhaFSS0I57W8X9FcC9PiHkhZZ4aAHWE5PhgV8q3A0JiJ4EFsOjtTktPA7LtSLGPSQXPF/vPTRwZY//NVc31VbrTGBOMUlgoIfHM2P/q7i32oe6px+ULqnafjuq00dw/D7+bTsjnfnfd79Jc5dDJJVFhrS0jKGmZssAdUqk8HV3ooQohQxztElyTvobyFizLCB3zUj7xQJQRWBbY81LVSCtYwtxrdeO6hA21wvJYt1sHX3xRok6WUhTQV5tOMCNlyhYA8ZnaD0g8CKeeIxOuUSNGZdu2USI3V7oo8s9KuF6SwLzrx9ZqNDC2DJNWLl3duBBBJsWp0Bx2c38heQByBe4N5gfNGUivcfgpyaXtRoJGHODmcMksqyDSL6lTAGTXT4J/QAg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
