env:
  global:
    - secure: k4MlFqSEt5RicQ8xcscgtpDiZCRORVidg0bFTaTQDLXOmmDTuDbq2pPMBVqANQhx5qUSLfdNsJTm8EX/JvQrrAhUQ3+N9M9HGc9YrtWIrTIy7L3X4LdMK0G59oeNaWbEJNLHu7Ns3iJSa5RKC2DpEYktwh4k7z4lcz3O+bOucWeXdE8Bo3l+cPoad9XwfYX2ct4J3044dS795YLjqrJEmz+SnE5FZGoUUmg/6q1tTUzxf0z16eYdveYRxqQBMxD2tjePXOlKnggeXzYXokyYbAldfU62S5gS05JOKQqkEfvkQNOJTPiLyB2+w9aVK8k4V/J0sYv6NG5CXERPakIOUwKueuB+J716tiMGFrPMwXhALtUOnIhJ9ovJwZoW2H1J0+Wn32DNATOkfuLxidB0k4fX1lYcXiB/Kfd/MBb5BZov2saHoZjtDWI64PyXKV+2OTjQ2FmBOCPbHy6APJ63nk80FJjIvaft7mqrZqluFfqO+l1Zlaxf7WaEl3JQ+R7LUPOo5x3Mw47iVbcOeFVW+vdMCvYpB6B7E+gNWrS+H0FlWSP8ihzucLT7FLOdzEY4P8/PTlo2pblBYvG1bGbAdkScmRGz76V2aG7wUBocTDXCpIuavNAOOighVgepsRojihsN1e3BcllfeMYReqn3utZ+VI7g+FmMQnrcAX2sb/g=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
