env:
  global:
    - secure: ktFiCSxDj9kj+gY8jW9nNi5EzFeoIogKCv8Tp5kyt53zfw1LCOooJ65S2sM+Rrdf/Fd1+tecfg7tCbwUXEqfMmyphrrIExJmdFAr7sFC9PQnabutWqSXRs6so7P9478AXqd6yevHqQxqYbdHyvAudt6k5IU3OCUpJohHBoOlMqJ64Z4QU6ScEIpFdQ0fy2I1iPI5mhhh2tv1cyBY+q8DHw1O39Q5wX5Gx9mgq7D8aFFUI//UIqBdEC8aAGd8ECpEhjJeDfe8LREdphzHS5eJNxjU/zlIGtLhztEk/giE4kad9twKEPx5tbgl0kOqMSOiex/EKud+OJnFBwmJMLtxVumrqgvJ2J/ngKMyODruQRMfsexQnZmoFWKkDNTTUSadz+VzmVCpg39ExJfOxrGVSw48CHE4l0+tD/odtOtja5c3L43t5GNHyUQU6OuytHxbKtQgJjgugxSCg+LnPEuWRrjNO4bGq/FJNpog67rhXRXy92eW2UAsEUuJuPyBebZjUoBrr5FYPo4kPcQhEMEcwLdTSGdG9aEsNCOomLASuA0G8qVkWAm+cgIXcpLgf33r+b/M1pcmyObbCYPLvAs2aYBAjOl86/FzV1HbBgRE6/E5EcVvuTLtAzVo3sRpYJ0rqUYfQ4JhKXvgnE/zrjn5aHi/Un4AsWRvpeHo7asK8QQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
