env:
  global:
    - secure: pewPcDkq9Eo7yAjpQh9Gl3ObZZyaqbiVGZHLQMKp+Ym5bSouchrGBENm7tPZ2GTr/2Cv25DEem4ACD0yekxTlRhNCIlOqsDqXWdvXMWGBVYXr2QpIZMnJg3rzXJzXnGg2rxunucgmQM/GBI1d/2zmFKSrG8JVbIKfk3rtNU6D6nJvA/eUEovosjS5KtdGM+wM92j46i6kCAFB3ZPSGlQ0RQD+qSPHv0sV4K6AoZSuodRWeYymThKVNzuY3PrfbrG4e8ykieCEakLXhlhuKcyTVvg4AVlxMfNj1lRUDchWrrQtEiZVSFYrqA2Eoqd/Un5WcG8jXE9fGU9Dbs+YRadX58QgktNrqWMoEFdjb/36PJcfKbea8a8hx/aha9u2RoMFqlFLqIwrQXbPxKBohfGVC50gFBkGAN/IjJ9O9YJglwux6sTRgLvcpqtb/ZbKnbcRym2MgHjDnklo244KFDv8hsFSpyfWvDLsfyzVADYgL3fH6Q9hU1NtPqXli/3FCO29WMo3xopAZZpB0KrR71O61/AgKzk59miwrcznwYdgT4hiInkhu7N828k/Yd+toScGA97HVOvPbfjKmw5x0+/PvHWwwro0xLOjV1PbygDwfkTE9tW2NcIRyPb2RpPjgTpXgMTIYy5fNxZCR/XVcihLNSLbRB2yq67Fi7AyurnD0k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
