env:
  global:
    - secure: g4CIyqaGOCR4XKQrjX8iP3ijJRjPgrJftCqmPfSU7rG80uFnjgYwfipFixaHqtIajHTHyD9RUizyBF54bChgiNvB41jy/BtHJi/3tH0zF6WmhH9H0mtCyJ+0oELSr3h+g8bTCLdOyu1cQ/PVb9VUFwgnAEie5XrFPZKAFoRGDA1iqkbiHz8Zvv3Tuxn+K48GYXdc0fSV40JRrHtL+DbOkEcDJTDWxFXPkuYaLoAooHD6HZbff3M/2pq5uALth13VItrIAI1RUlBxoy8Ji8DxjQ6Mrj/wdILwq3KWGVfscUUoX7k5nCc/j4Ub0Ahgmu7qgmR2JdtqeScpJOLb4Hwi/8vwGRqBu7nxDgZZ5J5cd2XXHF9hJsZ1Y8F741eCePzc5XQLKWYGyRYa0JsTSMnwbOSWtKmjHKvEJdWb7qpSz/jWX2b++f+LO6A6GgET8rBtvyALZYhYx46ffryH23Pv/H416Y0lejZMLCbvx1EmbcaCQf2lRxAtzRnlx3Ev16EXxa+PJ8LW6Tdq1DHiV29dZB3H4d8nvBHt1yl7n0TkSXx0IaUrQw7kljdFVSZgLx47ppEcvARiVRYxnFMatu+ZcoozgKyRPEA9c8YAGvkdduBldLUzIDUyJJNnkZozy6sB+OsZbbOdBy1/RbKn4LI7S91PeWCvNvtb2tfHrHtnZZY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
