env:
  global:
    - secure: Qsd3fCXEU/Kz2MqS4KUi6w7unR+7LHcXxXJJbzu0ySBLx5KtPWUEmGLuGV/hBhD+nToYwwwJqTd7JDKIMUoh8hymQAA8hsWKTA987CD8iq9WfhUtyeX4z+AT0C9tTt78UEQulfBWmXJkxhvC8wUdovfkIKRWF4xhWyGfkPcBxAbcqYAw4W5iwgBY19cbEddwaMswKB+6tZA0FRFqbWsqlGvQ5f7fqLFl61GTVvueGp2BLd420wO5pgYMQ8dUTeXfLxPKKrIG2neqisXLO/j3VL5PrElXBf/M0jvAeiSp30yv8uCrPVIrOyCWGq8Dm/O1J3/ONBsQyosayKQXPcoKSAyALP5wlmYf1GvInyw+W8bipopbvJhLenz75FQf/1+SHCLu0o7q/rqBDLn8AbIqMv/qY86IY/uGD5kspsIXsBOusFVJah7mBa3cWhwFz5OVqowyVMkT66g1Eg/eE3JJaXeqxcikLQzoprTtLxgRIHl/0Uxj44I1LC6BDs7vW4KuzvR2PMq/AhcAdHob9inabHdHdUV4ZulBvbh6jxcWy6O64aIqAAx+srXuUrDL3l+blGER+ARRlNGd/5/RrBf+/oQCdmJRah0I/938RS6fD6Gy39GjG6vBVdDjEvc9ZYijxHhA9+RFKxj4KdN+HkW3ebkjZzqd2biuaqctJTnmsI0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
