env:
  global:
    - secure: ot/9UibUC0ClFYgiXgw/7Bg3snLBVhKG0o0iyDJgiQQxKsMNeuqCH138UfAT3o6xeoV8b61R2h/I779cESh25RRBi3rG0CVSE8kxgVcJdY6J+x9w9jolRZD1FJjfSDpHikbnqGKgfpi8Wg/3gacxsJ1iJ8C9XFj5qk2PbLeoT8ciHmY0X8z9ZJQvLxJt2KDqY0buGLFVY1i0XuoCNmw53IkvlRlGwoI20ZmUmZDo+/WDW1wbWItBg4dEtO7zF6WCZhyTo9foxcf8A6Tw/9ExQvFjA8WH4+h6qL7stzzAGrJkFuugY0ZIbs4p0bossc8bzkvVYsTgx08SFdKeEQ1V60JeKzxoF0pDrrDZXEOlfW2dkHaS8BZEQLO45LiNWuA/Ov8VsXaIGVTgLoBL6OjH0UPjB4BfqomMRTGZznJLQCUkjlAQ8bzU7EzBPL2Xn/ZyLhhIuD92nyxvJSYZDhmwsy7pnMlWs2I4Fiz2sUu5O4SDs4yM92VhO9KGEqSW4xjSCQR+mzO6Vz0MSNXxk21x1CzP4YXupB1YvmZuTfytiYVOmhMHOVKT/tCpq2Rw0APqXNTLpBbVAPKTtQeYrNo2ypFR4kCHRNVBuLPQ7xrxLfufV9m1hP/wm7/EVxdupwq+TYXloX1dK0aqhMdKAVW2VsGOON1XnsHX1Qmn8Krr3qo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_5
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
